#!/usr/bin/env bash
# Displays FizzBuzz when the number is a multiple of 3 and 5
# Displays Fizz when the number is multiple of 3
# Displays Buzz when the number is a multiple of 5
k=1
while [ $k -le 100 ]
do
	if [ $((k % 5)) == 0 ] && [ $((k % 3)) == 0 ]
	then
		echo "FizzBuzz"
	elif [ $((k % 3 )) == 0 ]
	then
		echo "Fizz"
	elif [ $((k % 5)) == 0 ]
	then
		echo "Buzz"
	else
		echo "$k"
	fi
	k=$((k + 1))
done
